import fs from 'fs';
import path from 'path';

const DIST_DIR = path.resolve('dist/db');
const SRC_DIR = path.resolve('db');
const MLE_SRC_FILE = path.resolve('src/sneaker_logic.js');

function copyDir(src, dest) {
    if (!fs.existsSync(dest)) {
        fs.mkdirSync(dest, { recursive: true });
    }
    const entries = fs.readdirSync(src, { withFileTypes: true });

    for (let entry of entries) {
        let srcPath = path.join(src, entry.name);
        let destPath = path.join(dest, entry.name);

        if (entry.isDirectory()) {
            copyDir(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

try {
    console.log('Cleaning up build directory...');
    if (fs.existsSync('dist')) {
        fs.rmSync('dist', { recursive: true, force: true });
    }

    console.log('Copying database assets to build directory...');
    copyDir(SRC_DIR, DIST_DIR);

    console.log('Generating MLE module...');
    const jsContent = fs.readFileSync(MLE_SRC_FILE, 'utf8');
    // Ensure logic directory exists in dist
    const logicDistDir = path.join(DIST_DIR, 'logic');
    if (!fs.existsSync(logicDistDir)) {
        fs.mkdirSync(logicDistDir, { recursive: true });
    }

    const outMleFile = path.join(logicDistDir, 'mle_module.sql');

    const sqlContent = `--liquibase formatted sql

--changeset sneaker_dev:mle_deploy_v1 runAlways:true endDelimiter:/
--comment Deploy MLE Module (Auto-generated from src/sneaker_logic.js)
-- WARNING: DO NOT EDIT THIS FILE DIRECTLY. It is generated during build.

CREATE OR REPLACE MLE MODULE SNEAKER_LOGIC LANGUAGE JAVASCRIPT AS

${jsContent}
/

-- Check for errors and Raise if Invalid
DECLARE
    v_status VARCHAR2(20);
    v_err_msg VARCHAR2(4000);
BEGIN
    SELECT status INTO v_status FROM user_objects WHERE object_name = 'SNEAKER_LOGIC';
    
    IF v_status <> 'VALID' THEN
        FOR r IN (SELECT text, line, position FROM user_errors WHERE name = 'SNEAKER_LOGIC' ORDER BY sequence) LOOP
            v_err_msg := v_err_msg || 'Line ' || r.line || ': ' || r.text || CHR(10);
        END LOOP;
        raise_application_error(-20001, 'SNEAKER_LOGIC is INVALID: ' || CHR(10) || v_err_msg);
    END IF;
END;
/
`;

    fs.writeFileSync(outMleFile, sqlContent);
    console.log(`Successfully generated ${outMleFile}`);
    console.log('Build completed successfully.');

} catch (e) {
    console.error('Build failed:', e);
    process.exit(1);
}
