--liquibase formatted sql

--changeset sneaker_dev:tables_v1_sneakers
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM user_objects WHERE object_name = 'SNEAKERS'
CREATE TABLE sneakers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data JSON
);

--changeset sneaker_dev:tables_v1_orders
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM user_objects WHERE object_name = 'ORDERS'
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sneaker_id NUMBER,
    user_id VARCHAR2(100),
    amount NUMBER,
    ordered_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

--rollback DROP TABLE orders; DROP TABLE sneakers;
