--liquibase formatted sql

--changeset sneaker_dev:tables_v1
CREATE TABLE sneakers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data JSON
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sneaker_id NUMBER,
    user_id VARCHAR2(100),
    amount NUMBER,
    ordered_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

--rollback DROP TABLE orders; DROP TABLE sneakers;
