import fs from 'fs';
import path from 'path';

const SRC_FILE = path.resolve('src/mle/sneaker_logic.js');
const OUT_FILE = path.resolve('src/database/changelogs/20_mle_wrapper.sql');

try {
    const jsContent = fs.readFileSync(SRC_FILE, 'utf8');

    // Escape any Liquibase specific delimiters if necessary (not usually for / delimiter)
    // We mainly need to protect against nested block comments if they exist, but simple JS copy is usually fine.

    // Note: session.execute usage in JS is standard. 

    const sqlContent = `--liquibase formatted sql

--changeset sneaker_dev:mle_deploy_v1 runAlways:true endDelimiter:/
--comment Deploy MLE Module (Auto-generated from src/mle/sneaker_logic.js)
-- WARNING: DO NOT EDIT THIS FILE DIRECTLY. Edit src/mle/sneaker_logic.js and run 'npm run build'

CREATE OR REPLACE MLE MODULE SNEAKER_LOGIC LANGUAGE JAVASCRIPT AS

${jsContent}
/

-- Check for errors and Raise if Invalid
DECLARE
    v_status VARCHAR2(20);
    v_err_msg VARCHAR2(4000);
BEGIN
    SELECT status INTO v_status FROM user_objects WHERE object_name = 'SNEAKER_LOGIC';
    
    IF v_status <> 'VALID' THEN
        FOR r IN (SELECT text, line, position FROM user_errors WHERE name = 'SNEAKER_LOGIC' ORDER BY sequence) LOOP
            v_err_msg := v_err_msg || 'Line ' || r.line || ': ' || r.text || CHR(10);
        END LOOP;
        raise_application_error(-20001, 'SNEAKER_LOGIC is INVALID: ' || CHR(10) || v_err_msg);
    END IF;
END;
/

--rollback DROP MLE MODULE sneaker_logic;
`;

    fs.writeFileSync(OUT_FILE, sqlContent);
    console.log(`Successfully generated ${OUT_FILE}`);

} catch (e) {
    console.error('Build failed:', e);
    process.exit(1);
}
