-- 01_ddl.sql
-- Table definitions for SneakerHeadz Blitz

-- 1. Sneakers Table (JSON Document Store)
CREATE TABLE sneakers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data JSON CONSTRAINT sneakers_data_chk CHECK (data IS JSON)
);

-- 2. Orders Table (Relational)
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sneaker_id NUMBER REFERENCES sneakers(id),
    user_id VARCHAR2(100),
    amount NUMBER,
    ordered_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Index for JSON (FBI) will be added in 02_mle_module.sql after function definition if needed, 
-- or just standard functional index.
